// flow-typed signature: 1605452b55ff91429155a78eab2bf6eb
// flow-typed version: <<STUB>>/b64-to-blob_v^1.2.19/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'b64-to-blob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'b64-to-blob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'b64-to-blob/b64toBlob' {
  declare module.exports: any;
}

// Filename aliases
declare module 'b64-to-blob/b64toBlob.js' {
  declare module.exports: $Exports<'b64-to-blob/b64toBlob'>;
}
