// flow-typed signature: 51c1489a119ccddb1ae6e1530dfb3a63
// flow-typed version: <<STUB>>/cldr-data_v^32.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cldr-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cldr-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cldr-data/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cldr-data/index' {
  declare module.exports: $Exports<'cldr-data'>;
}
declare module 'cldr-data/index.js' {
  declare module.exports: $Exports<'cldr-data'>;
}
declare module 'cldr-data/install.js' {
  declare module.exports: $Exports<'cldr-data/install'>;
}
