// flow-typed signature: 893939fe56200d45fd953fe5bb8f0eba
// flow-typed version: <<STUB>>/npm-update-all_v^1.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-update-all'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-update-all' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-update-all/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-update-all/cli.js' {
  declare module.exports: $Exports<'npm-update-all/cli'>;
}
declare module 'npm-update-all/index' {
  declare module.exports: $Exports<'npm-update-all'>;
}
declare module 'npm-update-all/index.js' {
  declare module.exports: $Exports<'npm-update-all'>;
}
