// flow-typed signature: 9ae67304021c313353efe38f44059742
// flow-typed version: <<STUB>>/pa11y-reporter-html_v^1.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pa11y-reporter-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pa11y-reporter-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pa11y-reporter-html/lib/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pa11y-reporter-html/lib/reporter.js' {
  declare module.exports: $Exports<'pa11y-reporter-html/lib/reporter'>;
}
