// flow-typed signature: 28f4c25f08d780998c23694d42026b04
// flow-typed version: <<STUB>>/pa11y_v^5.0.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pa11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pa11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pa11y/bin/pa11y' {
  declare module.exports: any;
}

declare module 'pa11y/example/actions/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/basic/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/multiple/index' {
  declare module.exports: any;
}

declare module 'pa11y/example/puppeteer/index' {
  declare module.exports: any;
}

declare module 'pa11y/lib/action' {
  declare module.exports: any;
}

declare module 'pa11y/lib/pa11y' {
  declare module.exports: any;
}

declare module 'pa11y/lib/reporter' {
  declare module.exports: any;
}

declare module 'pa11y/lib/runner' {
  declare module.exports: any;
}

declare module 'pa11y/lib/vendor/HTMLCS' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-check-field.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-click-element.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-screen-capture.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-set-field-value.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-wait-for-element-event.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-wait-for-element-state.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/actions-wait-for-url.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/add-rule.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/config.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/environment.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/exit-codes.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/hide-elements.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/ignore.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/output.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/reporter-csv.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/reporter-json.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/root-element.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/screen-capture.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/standard.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/timeout.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/cli/wait.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/helper/pa11y-cli' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/issue/373.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/mock/website' {
  declare module.exports: any;
}

declare module 'pa11y/test/integration/setup.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/action.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/pa11y.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/reporter.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/lib/runner.test' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/action.mock' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/element.mock' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/fs-extra.mock' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/puppeteer.mock' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/util.mock' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/mock/window.mock' {
  declare module.exports: any;
}

declare module 'pa11y/test/unit/setup.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pa11y/bin/pa11y.js' {
  declare module.exports: $Exports<'pa11y/bin/pa11y'>;
}
declare module 'pa11y/example/actions/index.js' {
  declare module.exports: $Exports<'pa11y/example/actions/index'>;
}
declare module 'pa11y/example/basic/index.js' {
  declare module.exports: $Exports<'pa11y/example/basic/index'>;
}
declare module 'pa11y/example/multiple/index.js' {
  declare module.exports: $Exports<'pa11y/example/multiple/index'>;
}
declare module 'pa11y/example/puppeteer/index.js' {
  declare module.exports: $Exports<'pa11y/example/puppeteer/index'>;
}
declare module 'pa11y/lib/action.js' {
  declare module.exports: $Exports<'pa11y/lib/action'>;
}
declare module 'pa11y/lib/pa11y.js' {
  declare module.exports: $Exports<'pa11y/lib/pa11y'>;
}
declare module 'pa11y/lib/reporter.js' {
  declare module.exports: $Exports<'pa11y/lib/reporter'>;
}
declare module 'pa11y/lib/runner.js' {
  declare module.exports: $Exports<'pa11y/lib/runner'>;
}
declare module 'pa11y/lib/vendor/HTMLCS.js' {
  declare module.exports: $Exports<'pa11y/lib/vendor/HTMLCS'>;
}
declare module 'pa11y/test/integration/cli/actions-check-field.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-check-field.test'>;
}
declare module 'pa11y/test/integration/cli/actions-click-element.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-click-element.test'>;
}
declare module 'pa11y/test/integration/cli/actions-screen-capture.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-screen-capture.test'>;
}
declare module 'pa11y/test/integration/cli/actions-set-field-value.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-set-field-value.test'>;
}
declare module 'pa11y/test/integration/cli/actions-wait-for-element-event.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-wait-for-element-event.test'>;
}
declare module 'pa11y/test/integration/cli/actions-wait-for-element-state.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-wait-for-element-state.test'>;
}
declare module 'pa11y/test/integration/cli/actions-wait-for-url.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/actions-wait-for-url.test'>;
}
declare module 'pa11y/test/integration/cli/add-rule.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/add-rule.test'>;
}
declare module 'pa11y/test/integration/cli/config.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/config.test'>;
}
declare module 'pa11y/test/integration/cli/environment.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/environment.test'>;
}
declare module 'pa11y/test/integration/cli/exit-codes.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/exit-codes.test'>;
}
declare module 'pa11y/test/integration/cli/hide-elements.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/hide-elements.test'>;
}
declare module 'pa11y/test/integration/cli/ignore.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/ignore.test'>;
}
declare module 'pa11y/test/integration/cli/output.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/output.test'>;
}
declare module 'pa11y/test/integration/cli/reporter-csv.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/reporter-csv.test'>;
}
declare module 'pa11y/test/integration/cli/reporter-json.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/reporter-json.test'>;
}
declare module 'pa11y/test/integration/cli/root-element.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/root-element.test'>;
}
declare module 'pa11y/test/integration/cli/screen-capture.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/screen-capture.test'>;
}
declare module 'pa11y/test/integration/cli/standard.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/standard.test'>;
}
declare module 'pa11y/test/integration/cli/timeout.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/timeout.test'>;
}
declare module 'pa11y/test/integration/cli/wait.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/cli/wait.test'>;
}
declare module 'pa11y/test/integration/helper/pa11y-cli.js' {
  declare module.exports: $Exports<'pa11y/test/integration/helper/pa11y-cli'>;
}
declare module 'pa11y/test/integration/issue/373.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/issue/373.test'>;
}
declare module 'pa11y/test/integration/mock/website.js' {
  declare module.exports: $Exports<'pa11y/test/integration/mock/website'>;
}
declare module 'pa11y/test/integration/setup.test.js' {
  declare module.exports: $Exports<'pa11y/test/integration/setup.test'>;
}
declare module 'pa11y/test/unit/lib/action.test.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/action.test'>;
}
declare module 'pa11y/test/unit/lib/pa11y.test.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/pa11y.test'>;
}
declare module 'pa11y/test/unit/lib/reporter.test.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/reporter.test'>;
}
declare module 'pa11y/test/unit/lib/runner.test.js' {
  declare module.exports: $Exports<'pa11y/test/unit/lib/runner.test'>;
}
declare module 'pa11y/test/unit/mock/action.mock.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/action.mock'>;
}
declare module 'pa11y/test/unit/mock/element.mock.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/element.mock'>;
}
declare module 'pa11y/test/unit/mock/fs-extra.mock.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/fs-extra.mock'>;
}
declare module 'pa11y/test/unit/mock/puppeteer.mock.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/puppeteer.mock'>;
}
declare module 'pa11y/test/unit/mock/util.mock.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/util.mock'>;
}
declare module 'pa11y/test/unit/mock/window.mock.js' {
  declare module.exports: $Exports<'pa11y/test/unit/mock/window.mock'>;
}
declare module 'pa11y/test/unit/setup.test.js' {
  declare module.exports: $Exports<'pa11y/test/unit/setup.test'>;
}
