// @flow

export const SYSTEM_APICALLFAILURE: 'SYSTEM_APICALLFAILURE' = 'SYSTEM_APICALLFAILURE';

export const SYSTEM_ENVSETTINGS: 'SYSTEM_ENVSETTINGS' = 'SYSTEM_ENVSETTINGS';

export const SYSTEM_ROUTERLOCATION: 'SYSTEM_ROUTERLOCATION' = 'SYSTEM_ROUTERLOCATION';

export const SYSTEM_STYLES: 'SYSTEM_STYLES' = 'SYSTEM_STYLES';

export const SYSTEM_ZERPLEGACYMODE: 'SYSTEM_ZERPLEGACYMODE' = 'SYSTEM_ZERPLEGACYMODE';
