// @flow

export const ROUTER_HISTORY: 'ROUTER_HISTORY' = 'ROUTER_HISTORY';

export const ROUTER_NAVIGATIONBLOCKERSLISTADD: 'ROUTER_NAVIGATIONBLOCKERSLISTADD' = 'ROUTER_NAVIGATIONBLOCKERSLISTADD';

export const ROUTER_NAVIGATIONBLOCKERSLISTREMOVE: 'ROUTER_NAVIGATIONBLOCKERSLISTREMOVE' = 'ROUTER_NAVIGATIONBLOCKERSLISTREMOVE';

export const ROUTER_NAVIGATIONHASCHECK: 'ROUTER_NAVIGATIONHASCHECK' = 'ROUTER_NAVIGATIONHASCHECK';

export const ROUTER_NAVIGATIONISBLOCKED: 'ROUTER_NAVIGATIONISBLOCKED' = 'ROUTER_NAVIGATIONISBLOCKED';

export const ROUTER_NAVIGATIONREMOVECHECK: 'ROUTER_NAVIGATIONREMOVECHECK' = 'ROUTER_NAVIGATIONREMOVECHECK';

export const ROUTER_NAVIGATIONURLAFTERUNBLOCKED: 'ROUTER_NAVIGATIONURLAFTERUNBLOCKED' = 'ROUTER_NAVIGATIONURLAFTERUNBLOCKED';

export const ROUTER_PATHNAME: 'ROUTER_PATHNAME' = 'ROUTER_PATHNAME';
