// @flow

export const SINGLETONS_CONTEXTMENU: 'SINGLETONS_CONTEXTMENU' = 'SINGLETONS_CONTEXTMENU';

export const SINGLETONS_MFB: 'SINGLETONS_MFB' = 'SINGLETONS_MFB';

export const SINGLETONS_MODAL_NEXT: 'SINGLETONS_MODAL_NEXT' = 'SINGLETONS_MODAL_NEXT';

export const SINGLETONS_MODAL_PUSH: 'SINGLETONS_MODAL_PUSH' = 'SINGLETONS_MODAL_PUSH';

export const SINGLETONS_SNACKBAR_NEXT: 'SINGLETONS_SNACKBAR_NEXT' = 'SINGLETONS_SNACKBAR_NEXT';

export const SINGLETONS_SNACKBAR_PUSH: 'SINGLETONS_SNACKBAR_PUSH' = 'SINGLETONS_SNACKBAR_PUSH';

export const SINGLETONS_TOPACTIONBAR_PUSH: 'SINGLETONS_TOPACTIONBAR_PUSH' = 'SINGLETONS_TOPACTIONBAR_PUSH';
